# Generated by Django 5.0.2 on 2024-02-22 05:49

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='entry_questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.CharField(max_length=50)),
                ('a_option', models.CharField(max_length=50)),
                ('b_option', models.CharField(max_length=50)),
                ('c_option', models.CharField(max_length=50)),
                ('d_option', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='high_questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.CharField(max_length=50)),
                ('a_option', models.CharField(max_length=50)),
                ('b_option', models.CharField(max_length=50)),
                ('c_option', models.CharField(max_length=50)),
                ('d_option', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='middle_questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.CharField(max_length=50)),
                ('a_option', models.CharField(max_length=50)),
                ('b_option', models.CharField(max_length=50)),
                ('c_option', models.CharField(max_length=50)),
                ('d_option', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='puzzle_question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.CharField(max_length=50)),
                ('a_option', models.CharField(max_length=50)),
                ('b_option', models.CharField(max_length=50)),
                ('c_option', models.CharField(max_length=50)),
                ('d_option', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, null=True)),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('point', models.IntegerField(default=0)),
                ('entry', models.IntegerField(default=0)),
                ('middle', models.IntegerField(default=0)),
                ('high', models.IntegerField(default=0)),
                ('puzzle', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='entry_answers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('is_answer', models.BooleanField(default=True)),
                ('is_true', models.BooleanField(default=False)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foradmin.entry_questions')),
            ],
        ),
        migrations.CreateModel(
            name='high_answers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('is_answer', models.BooleanField()),
                ('is_true', models.BooleanField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foradmin.high_questions')),
            ],
        ),
        migrations.CreateModel(
            name='middle_answers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('is_answer', models.BooleanField()),
                ('is_true', models.BooleanField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foradmin.middle_questions')),
            ],
        ),
        migrations.CreateModel(
            name='puzzle_answers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('is_answer', models.BooleanField()),
                ('is_true', models.BooleanField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foradmin.puzzle_question')),
            ],
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
