# Generated by Django 5.0.2 on 2024-02-23 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foradmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry_answers',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foradmin.users'),
        ),
    ]
