# Generated by Django 5.0.2 on 2024-02-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foradmin', '0003_users_entry_count_users_high_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='entry_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='users',
            name='high_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='users',
            name='middle_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='users',
            name='puzzle_count',
            field=models.IntegerField(default=1),
        ),
    ]
